package com.kai.mybatis.pojo;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_1.id
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_1.title
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_1.author
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_1.update_time
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_1.Content
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_1.ImagePath
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    private String imagepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_1.type_id
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    private Integer typeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_1.id
     *
     * @return the value of news_1.id
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_1.id
     *
     * @param id the value for news_1.id
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_1.title
     *
     * @return the value of news_1.title
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_1.title
     *
     * @param title the value for news_1.title
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_1.author
     *
     * @return the value of news_1.author
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_1.author
     *
     * @param author the value for news_1.author
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_1.update_time
     *
     * @return the value of news_1.update_time
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_1.update_time
     *
     * @param updateTime the value for news_1.update_time
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_1.Content
     *
     * @return the value of news_1.Content
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_1.Content
     *
     * @param content the value for news_1.Content
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_1.ImagePath
     *
     * @return the value of news_1.ImagePath
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public String getImagepath() {
        return imagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_1.ImagePath
     *
     * @param imagepath the value for news_1.ImagePath
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public void setImagepath(String imagepath) {
        this.imagepath = imagepath == null ? null : imagepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_1.type_id
     *
     * @return the value of news_1.type_id
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_1.type_id
     *
     * @param typeId the value for news_1.type_id
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    public News(Integer id, String title, String author, String updateTime, String content, String imagepath, Integer typeId) {
        this.id = id;
        this.title = title;
        this.author = author;
        this.updateTime = updateTime;
        this.content = content;
        this.imagepath = imagepath;
        this.typeId = typeId;
    }

    public News() {
    }

    @Override
    public String toString() {
        return "News{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", author='" + author + '\'' +
                ", updateTime='" + updateTime + '\'' +
                ", content='" + content + '\'' +
                ", imagepath='" + imagepath + '\'' +
                ", typeId=" + typeId +
                '}';
    }
}