package com.kai.mybatis.pojo;

public class Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_1.type_id
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type_1.message
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_1.type_id
     *
     * @return the value of type_1.type_id
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_1.type_id
     *
     * @param typeId the value for type_1.type_id
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type_1.message
     *
     * @return the value of type_1.message
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type_1.message
     *
     * @param message the value for type_1.message
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    public Type(Integer typeId, String message) {
        this.typeId = typeId;
        this.message = message;
    }

    public Type() {
    }

    @Override
    public String toString() {
        return "Type{" +
                "typeId=" + typeId +
                ", message='" + message + '\'' +
                '}';
    }
}