package com.kai.mybatis.mapper;

import com.kai.mybatis.pojo.News;
import com.kai.mybatis.pojo.NewsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int countByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int deleteByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    List<News> selectByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    News selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int updateByExampleSelective(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int updateByExample(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int updateByPrimaryKey(News record);
}