package com.kai.mybatis.mapper;

import com.kai.mybatis.pojo.Type;
import com.kai.mybatis.pojo.TypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int countByExample(TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int deleteByExample(TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int insert(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int insertSelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    List<Type> selectByExample(TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    Type selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int updateByExampleSelective(@Param("record") Type record, @Param("example") TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int updateByExample(@Param("record") Type record, @Param("example") TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int updateByPrimaryKeySelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_1
     *
     * @mbggenerated Wed Mar 09 17:45:21 CST 2022
     */
    int updateByPrimaryKey(Type record);
}